(() => {
  const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
  let selected=null, conversations=[];
  const setStatus=(el,text,type)=>{el.textContent=text;el.className='status '+(type||'')};
  const fields=['displayName','responseLength','allowEmoji','publicGreeting','hqGreeting','publicRules','hqRules','suggestions','personality','approved_facts','faqs','official_links','escalation_rules','forbidden_claims'];
  function showView(name){$$('[data-panel]').forEach(p=>p.hidden=p.dataset.panel!==name);$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('#viewTitle').textContent={overview:'Overview',training:'Training & behavior',inbox:'Live inbox'}[name];if(name==='inbox')loadChats()}
  $$('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>showView(b.dataset.go));
  async function api(path,options){options=options||{};const r=await fetch(path,Object.assign({cache:'no-store'},options,{headers:Object.assign({'Content-Type':'application/json'},options.headers||{})}));const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Something went wrong.');return d}
  async function session(){try{const d=await api('/api/session');$('#userEmail').textContent=d.email||'Secure owner access'}catch(e){document.body.innerHTML='<main style="min-height:100vh;display:grid;place-items:center;background:#07080a;color:#f2f1ec;font:16px Arial"><section style="max-width:520px;padding:35px"><h1>Secure access required</h1><p style="color:#9ba1ad;line-height:1.6">This Xilo Control Center is owner-only. Sign in through Cloudflare Access with Ayden’s approved email.</p></section></main>'}}
  async function loadTraining(){setStatus($('#trainingStatus'),'Loading…');try{const d=await api('/api/xilo/admin/training');fields.forEach(k=>{const e=$('#'+k);if(e)e.type==='checkbox'?e.checked=!!d.training[k]:e.value=d.training[k]||''});setStatus($('#trainingStatus'),'Controls loaded.','ok')}catch(e){setStatus($('#trainingStatus'),e.message,'error')}}
  $('#reloadTraining').onclick=loadTraining;$('#trainingForm').onsubmit=async e=>{e.preventDefault();const training={};fields.forEach(k=>{const el=$('#'+k);training[k]=el.type==='checkbox'?el.checked:el.value.trim()});setStatus($('#trainingStatus'),'Saving…');try{await api('/api/xilo/admin/training',{method:'POST',body:JSON.stringify({training})});setStatus($('#trainingStatus'),'All Xilo controls saved.','ok')}catch(err){setStatus($('#trainingStatus'),err.message,'error')}};
  $$('[data-test]').forEach(b=>b.onclick=async()=>{const q=$('#testMessage').value.trim();if(!q)return;$('#testResult').textContent='Xilo is thinking…';try{const d=await api('/api/chat',{method:'POST',body:JSON.stringify({messages:[{role:'user',content:q}],pageUrl:b.dataset.test==='hq'?'https://yourfavalien.site/':'https://yourfavalien.com/',testMode:true})});$('#testResult').textContent=d.reply}catch(e){$('#testResult').textContent=e.message}});
  function renderChats(){const list=$('#chatList');list.innerHTML='';if(!conversations.length){list.innerHTML='<p style="padding:18px">No conversations yet.</p>';return}conversations.forEach(c=>{const b=document.createElement('button');b.className='chat-card'+(selected&&selected.id===c.id?' active':'');b.innerHTML='Visitor '+c.id.slice(0,6).toUpperCase()+'<small>'+(c.mode==='human'?'Ayden answering':'Xilo answering')+' · '+new Date(c.last_message_at||c.created_at).toLocaleString()+'</small>';b.onclick=()=>openChat(c);list.appendChild(b)})}
  async function loadChats(){try{const d=await api('/api/xilo/admin/conversations');conversations=d.conversations||[];$('#conversationCount').textContent=conversations.length;$('#humanCount').textContent=conversations.filter(c=>c.mode==='human').length;renderChats()}catch(e){setStatus($('#chatStatus'),e.message,'error')}}
  async function openChat(c){selected=c;renderChats();$('#chatTitle').textContent='Visitor '+c.id.slice(0,6).toUpperCase();$('#takeover').disabled=false;$('#takeover').textContent=c.mode==='human'?'Return to Xilo':'Take over';$('#reply').disabled=$('#sendReply').disabled=false;const d=await api('/api/xilo/admin/conversations/'+c.id);const box=$('#messages');box.innerHTML='';(d.messages||[]).forEach(m=>{const x=document.createElement('div');x.className='message '+m.sender;const small=document.createElement('small');small.textContent=m.sender==='ayden'?'You':m.sender==='xilo'?'Xilo':'Visitor';x.append(small,document.createTextNode(m.body));box.appendChild(x)});box.scrollTop=box.scrollHeight}
  $('#refreshChats').onclick=loadChats;$('#takeover').onclick=async()=>{if(!selected)return;const mode=selected.mode==='human'?'bot':'human';await api('/api/xilo/admin/conversations/'+selected.id+'/mode',{method:'POST',body:JSON.stringify({mode})});selected.mode=mode;openChat(selected)};
  $('#replyForm').onsubmit=async e=>{e.preventDefault();if(!selected)return;const body=$('#reply').value.trim();if(!body)return;await api('/api/xilo/admin/conversations/'+selected.id+'/reply',{method:'POST',body:JSON.stringify({body})});$('#reply').value='';selected.mode='human';openChat(selected)};
  session();loadTraining();loadChats();setInterval(()=>{if(!document.querySelector('[data-panel="inbox"]').hidden)loadChats()},6000);
})();
